### ISSUE TITLE
isLanguageEnglish gives true for spanish string, need to implement better solution

### ISSUE THREAD

**Issue by geeknotnerd** [geeknotnerd/techresource#30]
"ट्विटर पर Java Certification: \"Você é Certificado em #Java ?  Por que sim ou por que não ? Compartilhe suas opiniões http://t.co/vo76Xjnw6u http://t.co/tjHf3fC3JN\""

**Comment by geeknotnerd** [comment]
look at this answer http://stackoverflow.com/questions/16268986/check-if-a-string-is-an-english-word

**Comment by amitpagrawal** [comment]
Yes, we may check for char like é and

**Comment by geeknotnerd** [comment]
Fixed this-- on rekindled branch
